#!/bin/zsh

### Cure help.

function cure() {
    case "$1" in
         "version")
            echo "Cure version: $VERSION" 
            ;;
        "update")
            source "$func/modules-update" 
            ;;
        "upgrade")
            if [[ -d "$CURE_HOME" ]]; then
                git -C "$CURE_HOME" pull --quiet --ff --rebase --autostash
                echo "Cure self-update complete."

                source ${CURE_HOME}/init.zsh

                cure version
            else
                echo "CURE_HOME directory not found: $CURE_HOME"
            fi
            ;;
         "uninstall")
            echo "Uninstalling Cure..."
            sudo rm -rf "$CURE_HOME"

            echo "$CURE_HOME deleted."
            echo
            echo "Please remove this block of code from your .zshrc and restart your terminal"
            echo "--------------------------------------------------------------------------"
            echo "CURE_HOME=\${ZDOTDIR:-\${HOME}}/.cure"
            echo  
            echo "if [ ! -d "\$CURE_HOME" ]; then"
            echo "  git clone https://github.com/cgcoronel/cure \"\$CURE_HOME\""
            echo "fi"
            echo
            echo "source \${CURE_HOME}/init.zsh"
            echo "--------------------------------------------------------------------------"
            ;;
        *)
            echo "Usage: cure [update|upgrade|uninstall|version]"
            ;;
    esac
}



