#!/bin/zsh

### Update modules.

if [[ -d "$target_dir" ]]; then
    for repo init_file in "${(@kv)plugins}"; do
        repo_path="$target_dir/$repo"
        if [[ -d "$repo_path" ]]; then
            echo "Updating $repo"
            (cd "$repo_path" && git pull --quiet --ff --rebase --autostash)
        fi
    done
    source "${CURE_HOME}/init.zsh"
else
    echo "Cure directory not found: $target_dir"
fi

